# A generic, single database configuration for Alembic

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, inserted to sys.path if present
prepend_sys_path = .

# timezone to use when rendering dates in migration files
# timezone = UTC

# max length of characters in slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be detected as revisions
# sourceless = false

# version location specification
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator
# version_path_separator = os

sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/researchmind

[post_write_hooks]

[loggers]
keys = root,alembic,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
